# Generated by Django 5.1.1 on 2024-09-10 11:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('exercicio_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agrup_musc', models.TextField()),
                ('nome_exerc', models.CharField(max_length=30)),
                ('series', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('carga', models.IntegerField()),
                ('interv_seg', models.IntegerField()),
                ('tecnica_avanc', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Treinos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ExercicioInTreino',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordem', models.IntegerField()),
                ('series', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('carga', models.IntegerField()),
                ('intervalo_segs', models.IntegerField()),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.exercicios')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='treinos.treinos')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('treino', 'exercicio', 'ordem')},
            },
        ),
    ]
