# Generated by Django 5.1.1 on 2024-09-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0004_exercicios_treino_delete_exerciciointreino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicios',
            old_name='id',
            new_name='exercicio_id',
        ),
    ]
