# Generated by Django 5.1.1 on 2024-09-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0006_alter_exercicios_treino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicios',
            name='treino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='treinos.treinos'),
        ),
    ]
