# Generated by Django 5.1.1 on 2024-09-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0008_rename_exercicio_id_exercicios_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercicios',
            options={'ordering': ['created_on']},
        ),
    ]
