# Generated by Django 5.1.1 on 2024-10-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0009_alter_exercicios_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercicios',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='treinos',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='exercicios',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='treinos',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='exercicios',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='treinos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
