# Generated by Django 5.1.1 on 2024-10-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0010_alter_exercicios_options_alter_treinos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicios',
            name='agrup_musc',
            field=models.TextField(null=True),
        ),
    ]
